### ISSUE TITLE
Approach to implement categories and tags

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/plenti-educenter#17]
Hi @jimafisk 

I'm starting to think about how I should go about implementing `Categories` and `Tags` in this project. 
I think I like the idea of having named Categories and Tags and I know Roberto made this change in his `Compendium` theme. So possibly I could try to replicate that approach, what do you think? 

If so I see that he created a `catgs` and `tags` content folders and each `category` and `tag` got its own `.json` file with its name representing those tags and categories.  Inside each he had a `name` and `route` as follows:

```json
{
    "name": "Category Name",
    "route": "categories/category-name"
 }
```
Then I would need to have page templates for each in the `Content` folder such as `catgs.svelte` and `tags.svelte`. 
This could be a start.

Ben

**Comment by jamestagal** [comment]
Hi @jimafisk 
How are you?
Just wanted to let you know that I am back on the job and have started tackling tags and categories in this theme.  😄 

But when I started looking into the code, I saw an opportunity to create course categories like we had done on the `teacher_page.svelte` So in the `course_page.svelte` file I added it and I am happy to report it worked a charm. 😸 

I only had to add a placeholder zero ? (not sure of its name)`[0]` for the index because the `course.category` was in an array.
So like this:
```svelte
{#if !selectedCategory || selectedCategory === 'All' || selectedCategory === course.fields.course.category [0]}
```
Here is a short screencast of how it works.

https://user-images.githubusercontent.com/6309595/219309267-ba42adad-337d-4bc9-853b-5d6a33a88f1e.mov

**Comment by jamestagal** [comment]
Hi @jimafisk 
I hope you are good. Haven't heard from you in a while. 

I have implemented the Categories in this theme now but need some help to figure out how to get the Categories to load/update the posts. 

So I have created a ```blog_catgs.svelte``` [content file](https://github.com/jamestagal/plenti-educenter/blob/main/layouts/content/blog_catgs.svelte) and corresponding data source files. Then I have imported the ```aside.svelte``` [file ](https://github.com/jamestagal/plenti-educenter/blob/main/layouts/components/aside.svelte) into this ```blog_catgs``` template.  The posts do load but when clicking from one category to another from the ```aside``` the posts aren't being updated. I have to refresh the page manually to get them to update on the page. 

See screenshot example below for an illustration of the issue:
https://user-images.githubusercontent.com/6309595/225929041-6c1b506f-60ab-4cc3-843a-4ca713df9782.mov

Could you pls suggest a solution.
Regards,
Ben

**Comment by jamestagal** [comment]
Hi @jimafisk 
Looking at Roberto's implementation of Categories and Tags I have tried to do something similar. See what I have put in place below.

In ```aside.svelte``` I added a reactive variable 'catg'

```svelte
    $: catg = {
    name: content.fields.name,
    route: content.fields.route,
    posts: Object(catgPosts.filter((key) => key.name == content.fields.name)[0])
      .posts,
  };
```
Then further down in the template I created an ```#each``` block and targeted the ```path``` and ```name``` in the ```blog_catgs``` content as follows:

```svelte
        {#each Object(content => content.type == "blog_catgs") as { path, name }}
        <li class="border-bottom {(catg ? catg.name : '') == name ? 'active' : ''}" >
          <a
            href={path}
            class="d-block pb-3 mt-3">{name}</a
          >
        </li>
        {/each}
```
Also I imported both the ```aside.svelte``` and ```latest_articles``` in to both the ```blog_catgs``` and ```blog``` templates. see below.

```svelte
   <Aside {allContent} {content} {catg} {catgPosts}/>
   <LatestArticles {allContent} />
```

Firstly I don't know if this code actually works because as soon as I made these changes I got an error message, see below, but the massage seems reference a different svelte file so I am not sure why that might be.

Here is the error message:

```terminal
█▒▒▒▒▒▒▒▒▒ Building... 2023/03/18 18:25:40 build.go:153: 
Error in DataSource build step
Can't create props for content/blog.json 
Can't render htmlComponent for layouts_content_blog_svelte
TypeError: Cannot read property 'filter' of undefined
    at create_ssr:23:27
    at Object.$$render (create_ssr:1555:22)
    at create_ssr:65:96
    at Object.$$render (create_ssr:1555:22)
    at create_ssr:70:77
    at $$render (create_ssr:1555:22)
    at Object.render (create_ssr:1563:26)
    at create_ssr:1:58

```

Pls have a look into this when you can.

Chaers,
Ben

**Comment by jimafisk** [comment]
The `TypeError: Cannot read property 'filter' of undefined` leads me to believe that the `catgPosts` prop is not getting loaded correctly when calling `catgPosts.filter()`.

I'm kind of confused because I see you setting `catgPosts` as an exported prop in `layouts/content/blog_catgs.svelte` but I don't see the key in any of the corresponding content files located at `content/blog_catgs/`.

Maybe we should take a step back and describe exactly what we want to accomplish. I think it's:

1. Have an endpoint for each blog category
2. When visiting those endpoints, it should show a list of blog posts in that category

Is that correct? Can one blog post have more than one category?

**Comment by jimafisk** [comment]
Hi @jamestagal, I think my latest push gets you close to what you're looking for:

<details>
<summary>See gif</summary>

![categories](https://user-images.githubusercontent.com/5913244/226198992-79565b59-4e55-4984-93c2-e594af82a6c1.gif)


</details>

**Comment by jamestagal** [comment]
Hi @jimafisk 
Thank you so much for this fix and you simplified it greatly in the process.  
>1. Have an endpoint for each blog category 
>2. When visiting those endpoints, it should show a list of blog posts in that category

Yes that is exactly the goal. Though I am still grappling with knowing the correct language to use to describe it 😊
>Can one blog post have more than one category?

It might be nice ti have one blog post having more than one category but the example site doesn't so it might be ok to keep it the same.

Thanks again Jim.

**Comment by jamestagal** [comment]
Hi Jim,
Looking at the example site, I think I will need to implement one blog post having more than on ```Tag```.  I will try to set that up. i'll keep you posted.

BTW. I just notice today in this theme that I can't login to the CMS....I have updated to your latest release of Plenti v0.6.7. 
Have you experienced this issue since updating?

Ben

**Comment by jimafisk** [comment]
Hi @jamestagal,

Sorry I should have announced this, but `adminMenu` is no more. You can now access it with `$user.menu` (more compact and similar to `$user.login()` and `$user.logout()`. I just pushed a change for this, just let me know if it still gives you trouble! Thanks!

**Comment by jamestagal** [comment]
Hi @jimafisk 
All good. Nice change for consistency! Thanks for updating the code. 
Ben

**Comment by jamestagal** [comment]
Hi @jimafisk 
I have added tags to the posts however I think I haven't accounted for tags being in an array in the data source properly because I can't see any posts loading on the page.

I have added tags in an array in each post as follows:
```json
	"tag": [
		"AI",
		"Automation"
	]
```
and I have added a place holder `[0]` at the end of the `if` expression as follows in the ```blog_tags.svelte``` [file](https://github.com/jamestagal/plenti-educenter/blob/main/layouts/content/blog_tags.svelte) :

```svelte
{#if post.fields.tag === name [0]}
```

Please have a look when you can to see what I have missed 😊 

thanks,
Ben

**Comment by jimafisk** [comment]
Hi @jamestagal,

The `[0]` at the end is saying "give me the first item in this array." So you'd probably need to add that to `post.fields.tag[0]` since that's the array you created right? But I'm not sure that's the best way, since you'd only ever match the first item. Why not loop through the array and try to match the name like:
```svelte
{#each post.fields.tag as tag}
  {#if tag === name}
  {/if}
{/each}
```

**Comment by jamestagal** [comment]
Hi @jimafisk 

I am a little confused... why wouldn't this work, just looping over each for when ```tag``` is equal to ```name```:
```svelte
{#if post.fields.tag === name }

```
Ok I have tried to incorporate your suggestion into the code as follows but I get an error.

```svelte
<script>
    import Aside from "../components/aside.svelte";
    export let name, headerImage, allContent;
    let posts = allContent.filter(content => content.type === "posts");
</script>
<section
  class="page-title-section overlay"
  style="background-image:url({headerImage.url}),url({headerImage.url})"
>
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <ul class="list-inline custom-breadcrumb">
          <li class="list-inline-item h2">
            <a class="text-primary font-secondary" href="/">Home</a>
          </li>
          <li class="list-inline-item h5">
            <i class="ti-angle-right text-white" />
          </li>
          <li class="list-inline-item text-white h3 font-secondary">{name}</li>
        </ul>
      </div>
    </div>
  </div>
</section>
<section class="section">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 order-2 order-lg-1">
          <div class="row">
              {#each posts.fields.tag as tag}
              {#if tag === name}
              {#each posts as post}
                <div class="col-sm-6 mb-5">
                  <article
                    class="card rounded-0 border-bottom border-primary border-top-0 border-left-0 border-right-0 hover-shadow"
                  >
                    <a href={post.path}>
                      <img
                        class="card-img-top rounded-0"
                        src={post.fields.image.source}
                        alt={post.fields.image.alt}
                      /></a
                    >
                    <div class="card-body">
                      <ul class="list-inline mb-3">
                        <li class="list-inline-item mr-3 ml-0">
                          <i class="ti-calendar" />
                          {post.fields.publish.date}
                        </li>
                        <li class="list-inline-item mr-3 ml-0">
                          <i class="ti-user" />
                          <a href={post.fields.author.link}
                            >{post.fields.author.name}</a
                          >
                        </li>
                      </ul>
                      <h4 class="card-title">
                        <a href={post.path}>{post.fields.title}</a>
                      </h4>
                      <p class="card-text">
                        {post.fields.description
                          .substring(0, 150)
                          .replace(/(<([^>]+)>)/gi, "")}
                      </p>
                      <a href={post.path} class="btn btn-primary btn-sm"
                        >Read More</a
                      >
                    </div>
                  </article>
                </div>
                {/each}
              {/if}
            {/each}
          </div>
        </div>
        <Aside {allContent} />
          </div>
      </div>
  </section>
```

**Comment by jimafisk** [comment]
So I'm not actually looking at the full code, but if this is already in a loop over an array of `posts` you probably want something like:

```svelte
{#each posts as post}
  {#if post.fields.tag.includes(name)}
    <div class="date">{post.fields.publish.date}</div>
    <div class="author">{post.fields.author.name}</div>
    <div class="tags">
      {#each post.fields.tag as tag}
        <div class="tag">{tag}</div>
      {/each}
    </div>
  {/if}
{/each}
```

Just keep in mind the code above is just abbreviated pseudo-code to demonstrate. I also might consider renaming the `tag` key to `tags` since it's holding multiple values. Hope that helps!

**Comment by jamestagal** [comment]
Hi @jimafisk 
You are a legend 😸  yes that worked a treat! 
By including the ```includes``` method and passing the field ```(name)``` was a great approach.

Thanks again Jim. You are a life saver! 😊 
BTW. I will rename the ```tag``` to plural ```tags``` as that make a lot of sense.

Ben
